import "../globals.css";
import UserContext from "@/context/userContext";
import AlbumContext from "@/context/albumContext";
import SongContext from "@/context/songContext";
import Sidebar from "@/components/sidebar/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen w-full overflow-hidden font-mono">
        <UserContext>
          <AlbumContext>
            <SongContext>
              <Sidebar />
              {children}
            </SongContext>
          </AlbumContext>
        </UserContext>
      </body>
    </html>
  );
}
