import Sidebar from "@/components/sidebar/Sidebar";
import "../globals.css";
import UserContext, { AuthContext } from "@/context/userContext";
import { useContext } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen w-full font-mono">
        <UserContext>
          <Sidebar />
          {children}
        </UserContext>
      </body>
    </html>
  );
}
