import "@/app/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return <div className="flex h-screen w-full font-mono">{children}</div>;
}
