import "@/app/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen w-full font-mono">
        {children}
      </body>
    </html>
  )
}
