import AlbumContext from "@/context/albumContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  return <AlbumContext>{children}</AlbumContext>;
}
