import AlbumContext from "@/context/albumContext";
import SongContext from "@/context/songContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  return (
    <AlbumContext>
      <SongContext>{children}</SongContext>
    </AlbumContext>
  );
}
