import AuthProvider from "@/context/AuthProvider";
import "./globals.css";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body className="flex h-screen w-full overflow-hidden bg-gradient-to-br from-zinc-950 to-zinc-700 font-mono text-gray-50">
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
}
